### ISSUE TITLE
Regex to disallow wildcard certificates

### ISSUE THREAD

**Issue by ctrought** [cert-manager/approver-policy#149]
Is it currently possible? From what I read, I thought it might but when I tested it did not work as I expected.

https://cert-manager.io/docs/projects/approver-policy/

```
spec:
  allowed:
    commonName:
      required: true
      value: '*'
    dnsNames:
      required: true
      values:
      - "\*.domain.com"
```

I would like a certificate request consisting of a dnsName with the suffix `domain.com` to be allowed, but not a wildcard itself `*.domain.com`.

```
  - lastTransitionTime: "2022-10-25T18:41:53Z"
    message: 'No policy approved this request: [default-policy: spec.allowed.dnsNames.values:
      Invalid value: []string{"test-cert.domain.com"}: 
      \*.domain.com]'
```
