### ISSUE TITLE
Allow metrics to be scraped through prometheus annotations

### ISSUE THREAD

**Issue by bradfordwagner** [cert-manager/approver-policy#195]
Allow prometheus annotations to be used to scrape metrics from cert-manager-approver

```yaml
app:
  metrics:
    # new - unifies path between annotations and service - defaults to pre-existing path
    path: /metrics
    prometheus:
      # new - allows service discovery of metrics endpoint by annotation
      enabled: false
```
