### ISSUE TITLE
BUG: issuerRef `group: "cert-manager.io"` does not match CertificateRequest with no group.

### ISSUE THREAD

**Issue by inteon** [cert-manager/approver-policy#419]
approver-policy does not seem to be issuerRef group defaulting aware.

eg. the following policy will not match the example certificate request
```
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: selfsigned-policy
spec:
  ...
  selector:
    issuerRef:
      name: "internal-ca"
      kind: "ClusterIssuer"
      group: "cert-manager.io"
---
apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  name: test123
spec:
  ...
  issuerRef:
    kind: ClusterIssuer
    name: internal-ca
```
