### ISSUE TITLE
CEL: make validations have to match all elements in a list

### ISSUE THREAD

**Issue by felixkrohn** [cert-manager/approver-policy#423]
I want to create a CRP that allows multiple CR-dnsNames to match multiple RegExes.
- All dnsNames have to be validated by (at least) one validation
- One successful validation ought to be enough to validate each single dnsName
- a DNSname has not to successfully validate against all validations

As I find it difficult to find the precise words to describe what I want, I'll do with an example.

given the following CRP (excerpt):
```
spec:
  allowed:
    dnsNames:
      required: false
      validations:
        - message: only URIs matching the CR's namespace or *.example.com are allowed in dnsName
          rule: self.matches( '(\\.' + cr.namespace + '\\.svc(\\.cluster\\.local)?) || (.*\\.example.com)' )
```

☑️ When creating a Certificate in namespace 'foo' with single or multiple dnsNames out of `bar.foo.svc`, `bar.foo.svc.cluster.local`, or `foobar.example.com` the Certificate Request is approved, the policy works as expected.

🚫 When creating a Certificate with the following spec:

```
spec:
  dnsNames:
    - test.foo.svc.cluster.local
    - github.com
```
the Certificate Request is approved as well - meaning that as long as a single dnsName is validated, the Certificate is created.

This is obviously not what I intend.

Other variants I tried:
- having multiple validation rules: doesn't work, as then all of the dnsNames have to match all of the rules (the other extreme - all n:m validations have to succeed)
- multiple CRP: not tested, because if a single one validates a CR, others won't be tested

I havent' many more ideas, except maybe using OPA with some allOf/anyOf matching. Surely there must be a way of achieving the same with CEL?

Thanks!
