### ISSUE TITLE
CertificateRequestPolicy based on which namespace the certificate request belongs to

### ISSUE THREAD

**Issue by smuda** [cert-manager/approver-policy#62]
My use case is to only allow certificate requests with dnsName which are service-names from the namespace to which the service-name belongs to, for a certain cluster-issuer. For example the dnsName `my-service.my-space.svc` should only be allowed when requested from the "my-space" namespace.

Preferably, I'd also like to restrict namespaces for a certain cluster issuer.

I don't seem to find how to do that in the current implementation. Am I missing something or is this an uncommon usecase?

**Comment by rickymulder** [comment]
Is this issue still valid?  Looks like it was resolved in #96 
To accomplish this, there is a fairly complex rbac setup, but in order for a serviceaccount to make use of a request policy it must have the "use" action for the exact policy name.

**Comment by smuda** [comment]
Ops, I hadn't seen the PR. Let me check it out.

**Comment by sastorsl** [comment]
I would like to see an option where I can specify a fixed policy for a number of namespaces, without having to create a policy for all those namespaces.

An example would be that the `allowed` list could have placeholders.

Example policy:

```yaml
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: example-com
spec:
  allowed:
    # Name TBD - trigger that a <namespace> placeholder have to match the requesting namespace
    namespace_restricted: True
    commonName:
      value: "*.<namespace>.example.com"
    dnsNames:
      values:
      - "*.<namespace>.example.com"
    usages:
    - "server auth"
  selector:
    issuerRef:
      name: le-issuer
      kind: ClusterIssuer
      group: cert-manager.io
```

Should be allowed:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: my-test
spec:
  dnsNames:
  - my-certificate.my-test.example.com
  issuerRef:
    kind: ClusterIssuer
    name: le-issuer
  secretName: my-certificate
```

Should be rejected

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: my-othernamespace  # Namespace changed
spec:
  dnsNames:
  - my-certificate.my-test.example.com
  issuerRef:
    kind: ClusterIssuer
    name: le-issuer
  secretName: my-certificate
```

This would prevent:

* copy/paste errors
* One namespace grabbing or overwriting a hostname for one namespace into the other

Would achieve:

* Lock certificates to hostnames with their namespace in it only without managing complex and ever changing RBAC rules.
